SILENT=false; AUTO_PATH=false; AUTO_SRV=""; AUTO_MODE=""; ADDON_DIR=""
SETUP_COMPLETE=false; ENABLE_NOTIFS=false; HAS_ARGS=false; IS_TASK=false
IS_STEAM_LAUNCH=false; ENABLE_DISPLAY="true"; ENABLE_LOCAL_MODE=false

if [ -f "$CONFIG_FILE" ]; then source "$CONFIG_FILE"; fi

TTC_LAST_SALE="${TTC_LAST_SALE:-0}"
TTC_LAST_DOWNLOAD="${TTC_LAST_DOWNLOAD:-0}"
TTC_LAST_CHECK="${TTC_LAST_CHECK:-0}"
TTC_NA_VERSION="${TTC_NA_VERSION:-0}"
TTC_EU_VERSION="${TTC_EU_VERSION:-0}"
EH_LAST_SALE="${EH_LAST_SALE:-0}"
EH_LAST_DOWNLOAD="${EH_LAST_DOWNLOAD:-0}"
EH_LAST_CHECK="${EH_LAST_CHECK:-0}"
EH_LOC_5="${EH_LOC_5:-0}"; EH_LOC_7="${EH_LOC_7:-0}"; EH_LOC_9="${EH_LOC_9:-0}"
HM_LAST_DOWNLOAD="${HM_LAST_DOWNLOAD:-0}"
HM_LAST_CHECK="${HM_LAST_CHECK:-0}"
LOG_MODE="${LOG_MODE:-simple}"
EH_USER_TOKEN="${EH_USER_TOKEN:-}"
TTC_CLIENT_ID="${TTC_CLIENT_ID:-}"
TARGET_RUN_TIME="${TARGET_RUN_TIME:-0}"
TARGET_USERNAME="${TARGET_USERNAME:-}"
SKIP_DL_TTC="${SKIP_DL_TTC:-false}"
SKIP_DL_HM="${SKIP_DL_HM:-false}"
SKIP_DL_EH="${SKIP_DL_EH:-false}"
ENABLE_ADDON_UPDATES="${ENABLE_ADDON_UPDATES:-false}"
ADDON_LAST_CHECK="${ADDON_LAST_CHECK:-0}"
ADDON_UPDATE_SKIP="${ADDON_UPDATE_SKIP:-}"
AUTO_SELF_UPDATE="${AUTO_SELF_UPDATE:-true}"
SELF_LAST_CHECK="${SELF_LAST_CHECK:-0}"

write_lttc_config() {
    cat <<EOF > "$CONFIG_FILE"
AUTO_SRV="$AUTO_SRV"
SILENT=$SILENT
AUTO_MODE="$AUTO_MODE"
ADDON_DIR="$ADDON_DIR"
SETUP_COMPLETE=$SETUP_COMPLETE
ENABLE_NOTIFS=$ENABLE_NOTIFS
ENABLE_DISPLAY="$ENABLE_DISPLAY"
ENABLE_LOCAL_MODE=$ENABLE_LOCAL_MODE
LOG_MODE="$LOG_MODE"
TTC_LAST_SALE="$TTC_LAST_SALE"
TTC_LAST_DOWNLOAD="$TTC_LAST_DOWNLOAD"
TTC_LAST_CHECK="$TTC_LAST_CHECK"
TTC_NA_VERSION="$TTC_NA_VERSION"
TTC_EU_VERSION="$TTC_EU_VERSION"
EH_LAST_SALE="$EH_LAST_SALE"
EH_LAST_DOWNLOAD="$EH_LAST_DOWNLOAD"
EH_LAST_CHECK="$EH_LAST_CHECK"
EH_LOC_5="$EH_LOC_5"
EH_LOC_7="$EH_LOC_7"
EH_LOC_9="$EH_LOC_9"
HM_LAST_DOWNLOAD="$HM_LAST_DOWNLOAD"
HM_LAST_CHECK="$HM_LAST_CHECK"
EH_USER_TOKEN="$EH_USER_TOKEN"
TTC_CLIENT_ID="$TTC_CLIENT_ID"
TARGET_RUN_TIME="$TARGET_RUN_TIME"
TARGET_USERNAME="$TARGET_USERNAME"
SKIP_DL_TTC=$SKIP_DL_TTC
SKIP_DL_HM=$SKIP_DL_HM
SKIP_DL_EH=$SKIP_DL_EH
ENABLE_ADDON_UPDATES=$ENABLE_ADDON_UPDATES
ADDON_LAST_CHECK="$ADDON_LAST_CHECK"
ADDON_UPDATE_SKIP="$ADDON_UPDATE_SKIP"
AUTO_SELF_UPDATE=$AUTO_SELF_UPDATE
SELF_LAST_CHECK="$SELF_LAST_CHECK"
EOF
}

