$LTTC_SRC = $env:LTTC_SRC #src-only
. "$LTTC_SRC\lib\constants.ps1"
. "$LTTC_SRC\lib\esoui.ps1"
. "$LTTC_SRC\lib\console_interop.ps1"
. "$LTTC_SRC\lib\paths.ps1"
. "$LTTC_SRC\lib\single_instance.ps1"
. "$LTTC_SRC\lib\args.ps1"
. "$LTTC_SRC\lib\tray.ps1"
. "$LTTC_SRC\lib\config.ps1"
. "$LTTC_SRC\lib\logging.ps1"
. "$LTTC_SRC\lib\files.ps1"
. "$LTTC_SRC\lib\args_apply.ps1"
. "$LTTC_SRC\lib\addon_scan.ps1"
. "$LTTC_SRC\features\setup\wizard.ps1"
. "$LTTC_SRC\features\setup\startup.ps1"
. "$LTTC_SRC\data\kiosk_locations.ps1"
. "$LTTC_SRC\data\item_quality.ps1"
. "$LTTC_SRC\features\database\repair.ps1"
. "$LTTC_SRC\features\database\prune.ps1"
. "$LTTC_SRC\features\database\browser.ps1"
. "$LTTC_SRC\features\database\merge.ps1"
. "$LTTC_SRC\features\esohub\extract.ps1"
. "$LTTC_SRC\features\ttc\extract.ps1"
. "$LTTC_SRC\features\ttc\upload.ps1"
. "$LTTC_SRC\features\addons\updater.ps1"
. "$LTTC_SRC\features\self\update.ps1"
. "$LTTC_SRC\lib\runtime.ps1"
while ($true) {
    . "$LTTC_SRC\features\cycle\start.ps1"
    . "$LTTC_SRC\features\database\sync.ps1"
    if (!$global:ENABLE_LOCAL_MODE) { Invoke-AddonUpdates }
    . "$LTTC_SRC\features\ttc\update.ps1"
    . "$LTTC_SRC\features\esohub\update.ps1"
    . "$LTTC_SRC\features\harvestmap\update.ps1"
    . "$LTTC_SRC\features\cycle\cleanup.ps1"
    . "$LTTC_SRC\features\cycle\countdown.ps1"
}